[project]
name = "job-matcher"
version = "0.1.0"
description = ""
authors = [
    { name = "Anastasiia Odyntsova" }
]
requires-python = ">=3.11"

dependencies = [
    "kafka-python>=2.0.2",
    "sentence_transformers",
    "sqlalchemy",
    "pydantic",
    "pgvector",
    "psycopg",
    "uvicorn[standard]",
    "sqlalchemy[asyncio]",
    "pydantic[email]",
    "psycopg[binary]==3.2.9",
    "pydantic-settings==2.10.1",
    "python-docx",
    "pypdf"
]

[tool.uv]
dev-dependencies = [
    "pytest==8.4.1",
    "pre-commit==4.3.0"
]

[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"
